<a href="https://colab.research.google.com/github/RockChamps/DIABETES-PREDICTION-PROJECT/blob/main/assi10_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# DIABETES PREDICTION PROJECT |

# STEP 1: IMPORT LIBRARIES
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# STEP 2: LOAD DATASET
url = 'https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv'
df = pd.read_csv(url)
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [ ]:
df.tail(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
x=df.drop("Outcome",axis=1).astype('float64')
y=df["Outcome"].astype('int64')

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    float64
 1   Glucose                   768 non-null    float64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    float64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    float64
dtypes: float64(8)
memory usage: 48.1 KB

In [ ]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 768 entries, 0 to 767
Series name: Outcome
Non-Null Count  Dtype
--------------  -----
768 non-null    int64
dtypes: int64(1)
memory usage: 6.1 KB

In [ ]:
x.dropna()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0
...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0

In [ ]:
columns = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
for col in columns:
  x[col].replace(0, x[col].median(),inplace=True)

/tmp/ipython-input-1881007993.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x[col].replace(0, x[col].median(),inplace=True)

In [ ]:
print(x.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          6.0    148.0           72.0           35.0     30.5  33.6
1          1.0     85.0           66.0           29.0     30.5  26.6
2          8.0    183.0           64.0           23.0     30.5  23.3
3          1.0     89.0           66.0           23.0     94.0  28.1
4          0.0    137.0           40.0           35.0    168.0  43.1

   DiabetesPedigreeFunction   Age
0                     0.627  50.0
1                     0.351  31.0
2                     0.672  32.0
3                     0.167  21.0
4                     2.288  33.0

In [ ]:
print(y)
print(x)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6.0    148.0           72.0           35.0     30.5  33.6
1            1.0     85.0           66.0           29.0     30.5  26.6
2            8.0    183.0           64.0           23.0     30.5  23.3
3            1.0     89.0           66.0           23.0     94.0  28.1
4            0.0    137.0           40.0           35.0    168.0  43.1
..           ...      ...            ...            ...      ...   ...
763         10.0    101.0           76.0           48.0    180.0  32.9
764          2.0    122.0           70.0           27.0     30.5  36.8
765          5.0    121.0           72.0           23.0    112.0  26.2
766          1.0    126.0           60.0           23.0     30.5  30.1
767          1.0     93.0           70.0           31.0     30.5  30.4

     DiabetesPedigreeFunction   Age
0                       0.627  50.0
1                       0.351  31.0
2                       0.672  32.0
3                       0.167  21.0
4                       2.288  33.0
..                        ...   ...
763                     0.171  63.0
764                     0.340  27.0
765                     0.245  30.0
766                     0.349  47.0
767                     0.315  23.0

[768 rows x 8 columns]

In [ ]:
x.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns, index=x_train.index)
x_test_scaled  = pd.DataFrame(x_test_scaled,  columns=x_test.columns,  index=x_test.index)

In [ ]:
x_train_scaled.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
60,-0.526397,-1.256881,-0.018995,-0.454871,-0.612697,-0.050247,-0.490735,-1.035940
618,1.588046,-0.326051,0.808174,-0.340921,-0.612697,-0.598590,2.415030,1.487101
346,-0.828460,0.571536,-2.169636,-0.910670,-0.120429,-0.526439,0.549161,-0.948939
294,-1.130523,1.302903,-1.838768,-0.454871,-0.612697,-1.507685,-0.639291,2.792122
231,0.681856,0.405316,0.642740,1.140426,2.570636,1.998825,-0.686829,1.139095
340,-0.828460,0.272341,-0.184429,-1.594369,0.085855,-0.930482,0.008415,-0.948939
535,0.077730,0.338828,-0.018995,-0.454871,-0.612697,0.079624,-0.496677,-0.861938
306,1.890109,1.302903,-0.349863,-0.454871,0.339021,-0.988202,-0.425370,1.226097
718,-0.828460,-0.459026,-1.011599,2.165974,0.770342,0.454806,-0.160939,-0.774936
90,-0.828460,-1.389857,-1.425183,-0.454871,-0.612697,-1.911727,-0.627407,-1.035940

In [ ]:
x_test_scaled.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
668,0.681856,-0.791466,-1.177033,0.684627,0.882860,0.238355,-0.116372,0.878091
324,-0.526397,-0.326051,0.229156,0.570677,-0.612697,0.483666,-0.954231,-1.035940
624,-0.526397,-0.459026,-0.680731,-0.454871,-0.612697,-0.223408,-0.924520,-1.035940
690,1.285983,-0.492270,0.642740,-0.454871,-0.612697,-1.118073,1.149329,0.095078
473,0.983919,0.471804,1.469910,-0.454871,-0.612697,-0.353278,-0.770021,1.487101
204,0.681856,-0.625246,-0.018995,0.570677,0.882860,0.772268,-0.431312,1.922108
97,-0.828460,-1.689053,-2.004202,-1.024620,-0.186065,-1.724136,-0.434283,-0.948939
336,-1.130523,-0.159831,-0.018995,-0.454871,-0.612697,0.209495,1.375135,0.965092
568,0.077730,1.070196,-0.018995,0.228827,0.282762,-0.151257,-0.389716,0.356082
148,0.379793,0.837488,0.477306,-0.454871,-0.612697,0.195065,-0.746252,2.792122

***logistic regression***

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train_scaled, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy :", accuracy)

Accuracy : 0.7662337662337663

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[82 17]
 [19 36]]

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.83      0.82        99
           1       0.68      0.65      0.67        55

    accuracy                           0.77       154
   macro avg       0.75      0.74      0.74       154
weighted avg       0.76      0.77      0.77       154

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train_scaled, y_train)

RandomForestClassifier()

***K-Nearest Neighbors (KNN)***

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = model_knn.predict(x_test_scaled)
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=5)

KNN Accuracy: 0.7532467532467533
[[80 19]
 [19 36]]
              precision    recall  f1-score   support

           0       0.81      0.81      0.81        99
           1       0.65      0.65      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154

***SVM***

In [ ]:
from sklearn.svm import SVC

model_svm = SVC()
model_svm.fit(x_train_scaled, y_train)

SVC()

In [ ]:
y_pred_svm = model_svm.predict(x_test_scaled)

In [ ]:
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))
from sklearn.svm import SVC
model_svm = SVC()

SVM Accuracy: 0.7532467532467533
[[84 15]
 [23 32]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82        99
           1       0.68      0.58      0.63        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.72       154
weighted avg       0.75      0.75      0.75       154

***Decision Tree***

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier()
model_dt.fit(x_train, y_train)   # No scaling needed

DecisionTreeClassifier()

In [ ]:
y_pred_dt = model_dt.predict(x_test)

In [ ]:
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier()

Decision Tree Accuracy: 0.7272727272727273
[[74 25]
 [17 38]]
              precision    recall  f1-score   support

           0       0.81      0.75      0.78        99
           1       0.60      0.69      0.64        55

    accuracy                           0.73       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.74      0.73      0.73       154

***. Random Forest***

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier()
model_rf.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred_rf = model_rf.predict(x_test)

Random Forest Accuracy: 0.7467532467532467
[[78 21]
 [18 37]]
              precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154

***Gradient Boosting Classifier***

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

model_gb = GradientBoostingClassifier()
model_gb.fit(x_train, y_train)

GradientBoostingClassifier()

In [ ]:
y_pred_gb = model_gb.predict(x_test)

In [ ]:
print("Gradient Boosting Accuracy:", accuracy_score(y_test, y_pred_gb))
print(confusion_matrix(y_test, y_pred_gb))
print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))
from sklearn.ensemble import GradientBoostingClassifier
model_gb = GradientBoostingClassifier()

Gradient Boosting Accuracy: 0.7337662337662337
[[74 25]
 [16 39]]
[[74 25]
 [16 39]]
              precision    recall  f1-score   support

           0       0.82      0.75      0.78        99
           1       0.61      0.71      0.66        55

    accuracy                           0.73       154
   macro avg       0.72      0.73      0.72       154
weighted avg       0.75      0.73      0.74       154

***Naive Bayes (Gaussian NB)***

In [ ]:
from sklearn.naive_bayes import GaussianNB

model_nb = GaussianNB()
model_nb.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred_nb = model_nb.predict(x_test)
print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))
from sklearn.naive_bayes import GaussianNB
model_nb = GaussianNB()

Naive Bayes Accuracy: 0.7532467532467533
[[78 21]
 [17 38]]
              precision    recall  f1-score   support

           0       0.82      0.79      0.80        99
           1       0.64      0.69      0.67        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.74       154
weighted avg       0.76      0.75      0.76       154

***Bagging Classifier (with Decision Tree)***

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bagging = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    random_state=42
)

bagging.fit(x_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100,
                  random_state=42)

In [ ]:
y_pred_bag = bagging.predict(x_test)
print(classification_report(y_test, y_pred_bag))

              precision    recall  f1-score   support

           0       0.82      0.79      0.80        99
           1       0.64      0.69      0.67        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.74       154
weighted avg       0.76      0.75      0.76       154

***AdaBoost Classifier***

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier(n_estimators=200)
ada.fit(x_train, y_train)
print(classification_report(y_test, y_pred_bag))

AdaBoostClassifier(n_estimators=200)

In [ ]:
y_pred_ada = ada.predict(x_test_scaled)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_ada)
print("AdaBoost Accuracy :", accuracy)
from sklearn.metrics import confusion_matrix
cm_ada = confusion_matrix(y_test, y_pred_ada)
print(cm_ada)
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_ada))

AdaBoost Accuracy : 0.6428571428571429
[[99  0]
 [55  0]]
              precision    recall  f1-score   support

           0       0.64      1.00      0.78        99
           1       0.00      0.00      0.00        55

    accuracy                           0.64       154
   macro avg       0.32      0.50      0.39       154
weighted avg       0.41      0.64      0.50       154

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

***. Gradient Boosting***

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(x_train_scaled, y_train)
y_pred_gb = gb.predict(x_test_scaled)
accuracy = accuracy_score(y_test, y_pred_gb)
print("Gradient Boosting Accuracy :", accuracy)
cm_gb = confusion_matrix(y_test, y_pred_gb)
print(cm_gb)
print(classification_report(y_test, y_pred_gb))

Gradient Boosting Accuracy : 0.7337662337662337
[[74 25]
 [16 39]]
              precision    recall  f1-score   support

           0       0.82      0.75      0.78        99
           1       0.61      0.71      0.66        55

    accuracy                           0.73       154
   macro avg       0.72      0.73      0.72       154
weighted avg       0.75      0.73      0.74       154